###### 2021-04-01

# 01_Numpy Array 만들기

In [2]:
import numpy as np

## 1. Numpy Array 만들기

- `np.array()`

In [5]:
arr01 = np.array([1, 2, 3, 4])  # 항상 np.array() 안에는 []로 감싸주어야함
print(arr01)

arr02 = np.array((1, 2, 3, 4))  # ()로도 가능
print(arr02)

[1 2 3 4]
[1 2 3 4]


- `np.zero()`, `np.ones()`, `np.empty()`, `np.full()`

In [26]:
arr01 = np.zeros(10)
print(arr01)

arr02 = np.zeros((1, 2))
print(arr02)

arr03 = np.ones((2, 3, 4), dtype=np.int16)
print(arr03)

arr04 = np.empty((2, 3))
print(arr04)

arr05 = np.full((1, 10), 'a')
print(arr05)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]
[['a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a']]


- `np.zero_like()`, `np.empty_like()`, `np.ones_like()`, `np.full_like`

In [28]:
raw_arr = np.arange(1, 10, 1).reshape((3, 3))
print(raw_arr)

arr_zero_like = np.zeros_like(raw_arr)
print(arr_zero_like)

arr_ones_like = np.ones_like(raw_arr)
print(arr_ones_like)

arr_ones_like = np.empty_like(raw_arr)
print(arr_ones_like)

arr_full_like = np.full_like(raw_arr, 100)
print(arr_full_like)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[100 100 100]
 [100 100 100]
 [100 100 100]]


- np.arange()

In [10]:
arr = np.arange(1, 10, 1)  # 파이썬 일반 range와 쓰임이 같음
print(arr)

[1 2 3 4 5 6 7 8 9]


- np.linspace()

In [13]:
arr01 = np.linspace(0, 2, 9)  # 0에서 2사이의 구간을 9개로 나누어줌
print(arr01)

arr02 = np.linspace(0, 2*np.pi, 100)  # 0에서 2파이 사이의 구간을 100개로 나누어줌
print(arr02)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.394