###### 2021-04-01

# 02_Numpy Array 기본연산

In [1]:
import numpy as np

## array의 곱, 행렬곱

In [2]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

print(A * B)  # 원소 곱
print(A @ B)  # 행렬 곱 1
print(A.dot(B))  # 행력 곱 2

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


## Upcasting
- 데이터타입이 다른 값들을 더할때, 더욱 정교한 타입을 따름
- 예를들어 int + float = float

In [7]:
A = np.ones((2, 2), dtype=np.int16)
B = np.array([[0.1, 0.2], [0.3, 0.4]])
C = A + B

print(A)
print(B)
print(C)

print(A.dtype.name)
print(B.dtype.name)
print(C.dtype.name)

[[1 1]
 [1 1]]
[[0.1 0.2]
 [0.3 0.4]]
[[1.1 1.2]
 [1.3 1.4]]
int16
float64
float64


## 단항연산
- `min`, `max`, `sum`

In [10]:
A = np.array([[1, 2], [3, 4]])

print(A.min())
print(A.max())
print(A.sum())

1
4
10


## 특정 축에 대한 연산

In [11]:
A = np.array([[1, 2, 3], [4, 5, 6]])

print(A.min(axis=0))  # axis=0 : 칼럼
print(A.max(axis=1))  # axis=1 : 로우
print(A.sum(axis=0))

[1 2 3]
[3 6]
[5 7 9]
